name: Storybook GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use desired version of NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Build storybook
        run: npm run build-storybook -- -o ./storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook
          force_orphan: true
