name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-eslint:
    name: Lint ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Run tests
        run: npm run lint:eslint

  lint-prettier:
    name: Lint Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Run tests
        run: npm run lint:prettier
